Lazylist/config/urls.py
# encoding=utf-8

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    # Main Pages
    path(
        "",
        include("main.urls", namespace="main"),
    ),
    # User management
    path(
        "users/",
        include("users.urls", namespace="users"),
    ),
    path(
        "accounts/",
        include("allauth.urls"),
    ),
    # Django Admin, use {% url "admin:index" %}
    path(
        settings.ADMIN_URL,
        admin.site.urls,
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns

Lazylist/lazylist/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from main.views import (
    MovieLibraryView,
    MovieDetailView,
    MovieCreateView,
    MusicLibraryView,
    MusicDetailView,
    MusicCreateView,
    BookLibraryView,
    BookDetailView,
    BookCreateView,
)

app_name = "main"
urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/index.html"), name="index"),
    path("library", TemplateView.as_view(template_name="pages/pick-library.html"), name="library"),
    path("library/movies", MovieLibraryView.as_view(), name="movie"),
    path("library/movies/create", MovieCreateView.as_view(), name="movie-create"),
    path("library/movies/<slug:slug>", MovieDetailView.as_view(), name="movie-detail"),
    path("library/music", MusicLibraryView.as_view(), name="music"),
    path("library/music/create", MusicCreateView.as_view(), name="music-create"),
    path("library/music/<slug:slug>", MusicDetailView.as_view(), name="music-detail"),
    path("library/books", BookLibraryView.as_view(), name="book"),
    path("library/books/create", BookCreateView.as_view(), name="book-create"),
    path("library/books/<slug:slug>", BookDetailView.as_view(), name="book-detail"),
]

Lazylist/lazylist/users/urls.py
from django.urls import path

from .views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

Lazylist/lazylist/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Movie(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(editable=False, max_length=200)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug
        }
        return reverse("main:movie-detail", kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Music(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(editable=False, max_length=200)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug
        }
        return reverse("main:music-detail", kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Book(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(editable=False, max_length=200)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug
        }
        return reverse("main:book-detail", kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

Lazylist/lazylist/users/models.py
# encoding=utf-8

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

Lazylist/lazylist/main/forms.py
from django import forms
from main.models import Movie, Music, Book


class MovieForm(forms.Form):
    model = Movie
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title"}))


class MusicForm(forms.Form):
    model = Music
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title"}))


class BookForm(forms.Form):
    model = Book
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title"}))

Lazylist/lazylist/users/forms.py
# encoding=utf-8

from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")},
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

Lazylist/lazylist/main/views.py
from django.shortcuts import render
from main.models import Movie, Music, Book
from django.views.generic import CreateView, DetailView, ListView


class MovieLibraryView(ListView):
    model = Movie

    def get(self, request):
        movie = self.get_queryset().all()
        return render(request, "pages/movie-library.html", {"movie": movie})


class MovieDetailView(DetailView):
    model = Movie
    query_pk_and_slug = True

    def get(self, request, slug):
        movie = self.get_queryset().get(slug__iexact=slug)
        return render(request, "pages/movie-card.html", {"movie": movie})


class MovieCreateView(CreateView):
    model = Movie
    fields = "__all__"
    template_name = "pages/movie-form.html"


class MusicLibraryView(ListView):
    model = Music

    def get(self, request):
        music = self.get_queryset().all()
        return render(request, "pages/music-library.html", {"music": music})


class MusicDetailView(DetailView):
    model = Music
    query_pk_and_slug = True

    def get(self, request, slug):
        music = self.get_queryset().get(slug__iexact=slug)
        return render(request, "pages/music-card.html", {"music": music})


class MusicCreateView(CreateView):
    model = Music
    fields = "__all__"
    template_name = "pages/music-form.html"


class BookLibraryView(ListView):
    model = Book

    def get(self, request):
        book = self.get_queryset().all()
        return render(request, "pages/book-library.html", {"book": book})


class BookDetailView(DetailView):
    model = Book
    query_pk_and_slug = True

    def get(self, request, slug):
        book = self.get_queryset().get(slug__iexact=slug)
        return render(request, "pages/book-card.html", {"book": book})


class BookCreateView(CreateView):
    model = Book
    fields = "__all__"
    template_name = "pages/book-form.html"

Lazylist/lazylist/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

Lazylist/lazylist/templates/base-library.html
{% extends "base.html" %} {% load static i18n %}

<!-- Custom CSS -->
{% block css %}
{% endblock css %}

<!-- Body -->
{% block content %}
<!-- Header -->
<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url "main:index" %}">Lazylist</a>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
          {% if request.get_full_path == "/library/movies" %}
            <a button type="button" class="btn btn-primary cc" href="{% url "main:movie-create" %}">
              New Entry
            </a>
          {% elif request.get_full_path == "/library/music" %}
            <a button type="button" class="btn btn-primary cc" href="{% url "main:music-create" %}">
              New Entry
            </a>
          {% elif request.get_full_path == "/library/books" %}
            <a button type="button" class="btn btn-primary cc" href="{% url "main:book-create" %}">
              New Entry
            </a>
          {% endif %}
          </li>
          <li class="nav-item">
            {% if request.user.is_authenticated %}
              <a button type="button" class="btn btn-primary cc" href="{% url "account_logout" %}">
                Logout
              </a>
              <a button type="button" class="btn btn-primary cc" href="{% url "users:detail" request.user.username  %}">{% trans "My Profile" %}</a>
            {% else %}
              <a button type="button" class="btn btn-primary cc" href="{% url "account_login" %}">
                Login
              </a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<div class="container">
  <!-- Page Heading -->
  <h1 class="my-4">
    <strong>{% block library_name %}{% endblock library_name %}</strong>
  </h1>

  <div class="row">
    {% block view %}
    {% endblock view %}
  </div>
</div>
{% endblock content %}

Lazylist/lazylist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome Pro -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.12.1/css/all.css" integrity="sha384-TxKWSXbsweFt0o2WqfkfJRRNVaPdzXJ/YLqgStggBVRREXkwU7OKz+xXtqOU4u8+" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sriracha|Open+Sans|Oswald|Roboto&display=swap">

    <!-- Custom CSS -->
    {% block css %}{% endblock css %}

    <!-- Title -->
    <title>{% block title %}Lazylist{% endblock title %}</title>

  </head>

  <body>
    {% block content %}

    <!-- Bootstrap JS & Dependencies-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Custom Javascript -->
    {% block javascript %}{% endblock javascript %}

    {% endblock content %}
  </body>
</html>