Lazylist/config/urls.py
# encoding=utf-8

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    # Main Pages
    path(
        "",
        include("main.urls", namespace="main"),
    ),
    # User management
    path(
        "users/",
        include("users.urls", namespace="users"),
    ),
    path(
        "accounts/",
        include("allauth.urls"),
    ),
    # Django Admin, use {% url "admin:index" %}
    path(
        settings.ADMIN_URL,
        admin.site.urls,
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns

Lazylist/lazylist/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from main.views import (
    MovieLibraryView,
    MovieDetailView,
    MovieCreateView,
    MusicLibraryView,
    MusicDetailView,
    MusicCreateView,
    BookLibraryView,
    BookDetailView,
    BookCreateView,
)

app_name = "main"
urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/index.html"), name="index"),
    path("library", TemplateView.as_view(template_name="pages/pick-library.html"), name="library"),
    path("library/movies", MovieLibraryView.as_view(), name="movie"),
    path("library/movies/create", MovieCreateView.as_view(), name="movie-create"),
    path("library/movies/<slug:slug>", MovieDetailView.as_view(), name="movie-detail"),
    path("library/music", MusicLibraryView.as_view(), name="music"),
    path("library/music/create", MusicCreateView.as_view(), name="music-create"),
    path("library/music/<slug:slug>", MusicDetailView.as_view(), name="music-detail"),
    path("library/books", BookLibraryView.as_view(), name="book"),
    path("library/books/create", BookCreateView.as_view(), name="book-create"),
    path("library/books/<slug:slug>", BookDetailView.as_view(), name="book-detail"),
]

Lazylist/lazylist/users/urls.py
from django.urls import path

from .views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

Lazylist/lazylist/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Movie(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(editable=False, max_length=200)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug
        }
        return reverse("main:movie-detail", kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Music(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(editable=False, max_length=200)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug
        }
        return reverse("main:music-detail", kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Book(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(editable=False, max_length=200)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug
        }
        return reverse("main:book-detail", kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

Lazylist/lazylist/users/models.py
# encoding=utf-8

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

Lazylist/lazylist/main/forms.py
from django import forms
from main.models import Movie, Music, Book


class MovieForm(forms.Form):
    model = Movie
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title"}))


class MusicForm(forms.Form):
    model = Music
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title"}))


class BookForm(forms.Form):
    model = Book
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title"}))

Lazylist/lazylist/users/forms.py
# encoding=utf-8

from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")},
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

Lazylist/lazylist/main/views.py
from django.shortcuts import render
from main.models import Movie, Music, Book
from django.views.generic import CreateView, DetailView, ListView


class MovieLibraryView(ListView):
    model = Movie

    def get(self, request):
        movie = self.get_queryset().all()
        return render(request, "pages/movie-library.html", {"movie": movie})


class MovieDetailView(DetailView):
    model = Movie
    query_pk_and_slug = True

    def get(self, request, slug):
        movie = self.get_queryset().get(slug__iexact=slug)
        return render(request, "pages/movie-card.html", {"movie": movie})


class MovieCreateView(CreateView):
    model = Movie
    fields = "__all__"
    template_name = "pages/movie-form.html"


class MusicLibraryView(ListView):
    model = Music

    def get(self, request):
        music = self.get_queryset().all()
        return render(request, "pages/music-library.html", {"music": music})


class MusicDetailView(DetailView):
    model = Music
    query_pk_and_slug = True

    def get(self, request, slug):
        music = self.get_queryset().get(slug__iexact=slug)
        return render(request, "pages/music-card.html", {"music": music})


class MusicCreateView(CreateView):
    model = Music
    fields = "__all__"
    template_name = "pages/music-form.html"


class BookLibraryView(ListView):
    model = Book

    def get(self, request):
        book = self.get_queryset().all()
        return render(request, "pages/book-library.html", {"book": book})


class BookDetailView(DetailView):
    model = Book
    query_pk_and_slug = True

    def get(self, request, slug):
        book = self.get_queryset().get(slug__iexact=slug)
        return render(request, "pages/book-card.html", {"book": book})


class BookCreateView(CreateView):
    model = Book
    fields = "__all__"
    template_name = "pages/book-form.html"

Lazylist/lazylist/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

Lazylist/lazylist/templates/users/user_detail.html
{% extends "base.html" %}
{% load static i18n %}

<!-- Custom CSS -->
{% block css %}
<link href="https://fonts.googleapis.com/css?family=Fjalla+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Fjalla+One|Press+Start+2P&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static "css/user_detail.css" %}">
{% endblock css %}
<!-- Title -->
{% block title %}{{ object.username }}'s Profile{% endblock %}

<!-- Body -->
{% block content %}
<!-- <div class="container"> -->

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url "main:index" %}">lazylist</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url "main:index" %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url "users:detail" request.user.username  %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url "account_logout" %}">{% trans "Sign Out" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url "account_signup" %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url "account_login" %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    <!-- </div> -->
  </nav>

  <!-- Messages -->
  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %}
  {% endif %}

  <div class="rowuser">
    <div class="col-lg-12">
      <h2>Welcome {{ object.username }}!</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">
  <!-- <div class="userbuttons"> -->
    <div class= "info-section">
      <a class="myinfo btn btn-primary" href="{% url "users:update" %}" role="button">My Info</a>
    </div>
    <div class= "email-section">
      <a class="myinfo btn btn-primary" href="{% url "account_email" %}" role="button">E-Mail</a>
    </div>
    <div class = libary-section>
      <a class="myinfo btn btn-primary" href="{% url "main:library" %}" role="button">My Library</a>
    </div>
  <!-- </div> -->

</div>
<!-- End Action buttons -->
{% endif %}

<!-- Footer -->
<footer class="bottom">
    <p>&copy; 2020 lazylist, Inc. All rights reserved.</p>
    <a href="terms">Terms</a>
    <a href="privacy">Privacy</a>
    <a href="help">Help</a>
  </footer>
</div>
{% endblock content %}

Lazylist/lazylist/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static i18n %}

<!-- Custom CSS -->
{% block css %}
<link href="https://fonts.googleapis.com/css?family=Fjalla+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Fjalla+One|Press+Start+2P&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static "css/user_detail.css" %}">
{% endblock css %}


{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>Hello {{ user.username }}! Need to update your username?</h1>
  <form class="form-horizontal" method="post" action="{% url "users:update" %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-success btn-lg cc">Update</button>
      </div>
    </div>
  </form>
{% endblock %}